# -*- coding: utf-8 -*-
"""raw_plus_maps_data_compiler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPAmfvXWEAWPI_hY9PVnwsC9OpFm-E9s
"""

from csv import reader
import pandas as pd
df = pd.DataFrame()
link_data=list()

with open('link_and_code_26th_march.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    link_data = list(csv_reader)

link_data=link_data[1:]

with open('central_data.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    central_data = list(csv_reader)
    for i in range (0,len(central_data)):
      item=central_data[i]
      NS_code=item[1]
      flag=0
      for j in range (0,len(link_data)):
        if( int(NS_code) == int(link_data[j][0]) ):
          print(NS_code,link_data[j][1])
          flag=1
          df=df.append({'NS_code':item[1],
                        'District':item[2],
                        'Address':item[3],
                        'Google Maps Link':link_data[j][1],
                        'Capacity':item[5],
                        'Type':item[4],
                        'Division':item[7],
                        'Name of Agency':item[9],
                        'Purpose':item[8],
                        'Area (Sq. Ft.)':item[6]
                        }, ignore_index=True)
      if(flag==0):
          print(NS_code,'')
          df=df.append({'NS_code':item[1],
                        'District':item[2],
                        'Address':item[3],
                        'Google Maps Link':'Not Available currently',
                        'Capacity':item[5],
                        'Type':item[4],
                        'Division':item[7],
                        'Name of Agency':item[9],
                        'Purpose':item[8],
                        'Area (Sq. Ft.)':item[6]
                        }, ignore_index=True)
          

print(df)

df.to_csv('delhi_shelters_with_maps_link_updated.csv', columns=['NS_code','District','Address','Google Maps Link','Capacity','Purpose','Area (Sq. Ft.)','Type','Division','Name of Agency'],index=True)